[project]
name = "nanochat-repro"
version = "0.1.0"
description = "From-scratch reproduction of Andrej Karpathy nanochat"
readme = "README.md"
license = "MIT"
authors = [{ name = "Marcin Bogdanski" }]
requires-python = ">=3.12"
dependencies = [
  "ipykernel==7.1.0",
  "torch==2.9.1",
  "matplotlib==3.10.8",
  "tiktoken==0.12.0",
  "datasets==4.4.2",
  "rustbpe==0.1.0",
  "wandb==0.24.2",
  "kernels==0.11.7",
  "tabulate==0.10.0",
  "pydot==4.0.1",
  "ipympl==0.10.0",
  "nvtx==0.2.16",
]

# Don't allow non-wheel installs (no compile from source)
[tool.uv.pip]
# Alias for --only-binary :all:
no-build = true
