"""Post-process the Nsight Systems trace generated by `example_nsight.py`.

This script injects GPU-side phase spans based on the recorded CUDA events and NVTX markers.

The steps are as follows:
- grab CPU-side of CUDA event and corresponding NVTX markers
- track CPU-side CUDA event API call and correlate with GPU-side events
- generate new "virtual" GPU-side phase spans, based on GPU-side events
- write the augmented trace to new file: `example_nsight_gpu_spans.nsys-rep`

Run both parts:
uv run dev/example_nsight.sh
"""
import os
import sys
import shutil
from pathlib import Path

def setup_nsys_writer():
    """Set up the Nsight Systems writer environment.
    
    Nsight Systems is typically downloaded as .deb file and installed via package manager.
    The Nsight Systems includes the command-line tools, Python packages, and backend shared libraries.
    The ceremony below is needed to find the path to the Python package, and inform it about the location of the backend shared library.
    """
    nsys_link = Path(shutil.which("nsys"))  # symlink:                  /usr/local/bin/nsys
    nsys = nsys_link.resolve()              # binary:                   /opt/nvidia/nsight-systems-cli/2026.4.1/target-linux-x64/nsys
    nsys_target = nsys.parent               # Nsight binaries/packages: /opt/nvidia/nsight-systems-cli/2026.4.1/target-linux-x64
    nsys_root = nsys_target.parent          # Nsight root:              /opt/nvidia/nsight-systems-cli/2026.4.1

    # /opt/nvidia/nsight-systems-cli/2026.4.1/target-linux-x64/python/packages
    writer_packages = nsys_target / "python" / "packages"

    # /opt/nvidia/nsight-systems-cli/2026.4.1/host-linux-x64/libNvtxwBackend.so
    writer_backend = nsys_root / "host-linux-x64" / "libNvtxwBackend.so"

    # Insert the Nsight writer Python packages into the path - so we can import nsys_writer
    sys.path.insert(0, str(writer_packages))
    # Set env var, so the Nsight writer knows where to find the backend shared library
    os.environ["NSYS_WRITER_BACKEND"] = str(writer_backend)
setup_nsys_writer()

from nsys_writer import Session, TimeBase

print("WOOT!")