"""Post-process the Nsight Systems trace generated by `example_nsight.py`.

This script injects GPU-side phase spans based on the recorded CUDA events and NVTX markers.

The steps are as follows:
- grab CPU-side of CUDA event and corresponding NVTX markers
- track CPU-side CUDA event API call and correlate with GPU-side events
- generate new "virtual" GPU-side phase spans, based on GPU-side events
- write the augmented trace to new file: `example_nsight_gpu_spans.nsys-rep`

See complete example:
uv run dev/example_nsight.sh
"""
print("--------------------------------------------------------------------------------")
print("                     Post-processing Nsight Systems Trace")
print("--------------------------------------------------------------------------------")
import os
import sys
import shutil
import sqlite3
import tempfile
import subprocess
from collections import defaultdict
from pathlib import Path

def setup_nsys_writer():
    """Set up the Nsight Systems writer environment.
    
    Nsight Systems is typically downloaded as .deb file and installed via package manager.
    The Nsight Systems includes the command-line tools, Python packages, and backend shared libraries.
    The ceremony below is needed to find the path to the Python package, and inform it about the location of the backend shared library.
    """
    nsys_link = Path(shutil.which("nsys"))  # symlink:                  /usr/local/bin/nsys
    nsys = nsys_link.resolve()              # binary:                   /opt/nvidia/nsight-systems-cli/2026.4.1/target-linux-x64/nsys
    nsys_target = nsys.parent               # Nsight binaries/packages: /opt/nvidia/nsight-systems-cli/2026.4.1/target-linux-x64
    nsys_root = nsys_target.parent          # Nsight root:              /opt/nvidia/nsight-systems-cli/2026.4.1

    # /opt/nvidia/nsight-systems-cli/2026.4.1/target-linux-x64/python/packages
    writer_packages = nsys_target / "python" / "packages"

    # /opt/nvidia/nsight-systems-cli/2026.4.1/host-linux-x64/libNvtxwBackend.so
    writer_backend = nsys_root / "host-linux-x64" / "libNvtxwBackend.so"

    # Insert the Nsight writer Python packages into the path - so we can import nsys_writer
    sys.path.insert(0, str(writer_packages))
    # Set env var, so the Nsight writer knows where to find the backend shared library
    os.environ["NSYS_WRITER_BACKEND"] = str(writer_backend)
setup_nsys_writer()

from nsys_writer import Session, TimeBase  # pyright: ignore[reportMissingImports]


source_filename = sys.argv[1]  # e.g. example_nsight.nsys-rep
output_filename = sys.argv[2]  # e.g. example_nsight_gpu_spans.nsys-rep
assert source_filename.endswith(".nsys-rep"), "Source file must be an Nsight Systems report (.nsys-rep)"
assert output_filename.endswith(".nsys-rep"), "Output file must be an Nsight Systems report (.nsys-rep)"

# Convert the Nsight Systems trace to a SQLite database for post-processing
with tempfile.TemporaryDirectory() as temp_dir:
    temp_filepath = Path(temp_dir) / "example_nsight.sqlite"
    print(f"Exporting SQLite database to: {temp_filepath}")
    subprocess.run(["nsys", "export", "--type=sqlite", "--force-overwrite=true", "--quiet=true", f"--output={temp_filepath}", source_filename], check=True)

    # Agent supplied query to extract custom NVTX events and their corresponding CUDA event timestamps
    query = """
        WITH markers AS (
            SELECT
                n.start,
                n.end,
                n.globalTid,
                ((n.globalTid >> 24) << 24) AS globalPid,
                coalesce(n.text, marker_string.value) AS label
            FROM NVTX_EVENTS AS n
            LEFT JOIN StringIds AS marker_string ON marker_string.id = n.textId
            WHERE coalesce(n.text, marker_string.value) LIKE 'custom_event rank=%'
        )
        SELECT
            markers.label,
            cuda_event.timestamp
        FROM markers
        JOIN CUPTI_ACTIVITY_KIND_RUNTIME AS runtime
            ON runtime.globalTid = markers.globalTid
            AND runtime.start >= markers.start
            AND runtime.end <= markers.end
        JOIN StringIds AS runtime_string
            ON runtime_string.id = runtime.nameId
            AND runtime_string.value LIKE 'cudaEventRecord%'
        JOIN CUPTI_ACTIVITY_KIND_CUDA_EVENT AS cuda_event
            ON cuda_event.correlationId = runtime.correlationId
            AND cuda_event.globalPid = markers.globalPid
        ORDER BY cuda_event.timestamp
    """
    with sqlite3.connect(temp_filepath) as conn:
        rows = conn.execute(query).fetchall()

print("Rows extracted from SQLite database:")
for row in rows:
    print(row)
# ('custom_event rank=0 forward.begin', 17439452)
# ('custom_event rank=1 forward.begin', 17898137)
# ('custom_event rank=0 forward.end', 25270603)
# ('custom_event rank=0 backward.begin', 25274507)
# ('custom_event rank=1 forward.end', 25768294)
# ('custom_event rank=1 backward.begin', 25771494)
# ('custom_event rank=0 backward.end', 34541122)
# ('custom_event rank=0 comms.begin', 34544386)
# ('custom_event rank=1 backward.end', 35051548)
# ('custom_event rank=1 comms.begin', 35054716)
# ('custom_event rank=1 comms.end', 100817205)
# ('custom_event rank=1 optimizer.begin', 100820373)
# ('custom_event rank=0 comms.end', 101217837)
# ('custom_event rank=0 optimizer.begin', 101221133)
# ('custom_event rank=1 optimizer.end', 102420286)
# ('custom_event rank=0 optimizer.end', 102815255)
# ...

# Color Dispenser
def get_color(name):
    colors = {
        "forward": "#4CAF50",
        "backward": "#41C4D5",
        "optimizer": "#F4A261",
        "adamw": "#F4A261",
        "muon": "#D16767",
    }
    for k, v in colors.items():
        if k in name:
            return v
    return "#747474"  # default color if no match is found

# Extract start and end events from the rows
timestamps = defaultdict(list)  # (rank, name) -> [[start_ts, end_ts], [start_ts, end_ts], ...]
for label, timestamp in rows:
    _, rank_str, name_and_phase = label.split()
    rank = int(rank_str.split('=')[1])
    name, phase = name_and_phase.split('.')
    if phase == "begin":
        assert len(timestamps[(rank, name)]) == 0 or timestamps[(rank, name)][-1][1] is not None, "Previous event has not ended"
        timestamps[(rank, name)].append([timestamp, None])
    elif phase == "end":
        assert len(timestamps[(rank, name)]) > 0 and timestamps[(rank, name)][-1][1] is None, "No matching start event for this end event"
        timestamps[(rank, name)][-1][1] = timestamp
    else:
        raise ValueError(f"Unexpected phase: {phase}")
max_rank = max(rank for rank, _ in timestamps.keys())
assert all(start_ts is not None and end_ts is not None for intervals in timestamps.values() for start_ts, end_ts in intervals)

# Write Output Session
with Session(
    name=output_filename.replace(".nsys-rep", ""),
    report_merge=source_filename,
    time_base=TimeBase.RELATIVE,
) as session:
    domain = session.get_domain("Derived GPU spans")
    for rank in range(max_rank + 1):
        scope = domain.get_scope(f"rank {rank}")
        with session.create_stream("phases", domain=domain, scope=scope) as stream:
            for (r, name), intervals in timestamps.items():
                if r != rank:
                    continue
                for start_ts, end_ts in intervals:
                    stream.write_startend(start_ts, end_ts, message=name, color=get_color(name))
